services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: gestionusuarios
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pgetroot"]
      timeout: 5s
      retries: 5
    networks:
      - gestion-network

  spring_app:
    build: .
    container_name: spring_app_container
    restart: always
    ports:
      - "8080:8080"
    environment:
    - DB_URL=jdbc:mysql://mysql_db:3306/gestionusuarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    - DB_USERNAME=root
    - DB_PASSWORD=root
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - gestion-network

networks:
  gestion-network:
    driver: bridge